### 판다스 기초

#### 판다스 패키지로드

In [3]:
import pandas as pd
import numpy as np

#### 핵심 자료구조
- `Series`와 `DataFrame`

#### Series

- 1차원 데이터를 표현하는 자료구조. `인덱스`가 붙어있는 한줄짜리 데이터. 1차원 배열과 흡사

In [4]:
np_scores = np.array([85, 90, 95, 80])

np_scores

array([85, 90, 95, 80])

In [5]:
scores = pd.Series([85, 90, 95, 80])

scores

0    85
1    90
2    95
3    80
dtype: int64

- 시리즈

In [6]:
scores = pd.Series(
    [85,90,95,80],
    index=['홍길동','김철수','이영희','박민수']
)

scores

홍길동    85
김철수    90
이영희    95
박민수    80
dtype: int64

In [8]:
# 인덱스가 숫자에서 문자열로 변경
scores['홍길동']

np.int64(85)

#### Series 연산

In [9]:
scores + 5

홍길동     90
김철수     95
이영희    100
박민수     85
dtype: int64

In [10]:
scores / 2

홍길동    42.5
김철수    45.0
이영희    47.5
박민수    40.0
dtype: float64

In [14]:
scores * 2

홍길동    170
김철수    180
이영희    190
박민수    160
dtype: int64

In [17]:
scores.mean()

np.float64(87.5)

In [18]:
scores.min()

np.int64(80)

In [19]:
scores.max()

np.int64(95)

In [20]:
scores.count()

np.int64(4)

- NumPy와 통계함수가 거의 유사하게 존재
- 속도문제로 예전에는 NumPy를 많이 이용했지만, 현재는 사용효율 높지 않음

#### DataFrame
- Pandas 2차원 표형태 데이터 표현하는 자료구조
- Pandas의기본 자료구조형
- 엑셀, CSV(엑셀형태 텍스트파일), DB 테이블과 거의 동일한 구조

In [26]:
# DataFrame을 직접 생성할때 사용.
raw_data = {
 'name' : ['홍길동', '김철수', '이영희', '박민수', '성유고', '애슐리'],
 'age' : [20, 21, 22, 23, 25, 26],
 'major' : ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score' : [85, 90, 95, 80, 100, 75]
}

raw_data

{'name': ['홍길동', '김철수', '이영희', '박민수', '성유고', '애슐리'],
 'age': [20, 21, 22, 23, 25, 26],
 'major': ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score': [85, 90, 95, 80, 100, 75]}

In [27]:
#일반적으로 DataFrame 줄여서 df로 변수명 많이 활용
df = pd.DataFrame(raw_data)

df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   25   인공지능    100
5  애슐리   26    웹개발     75

#### DataFrame 구조 확인
- NumPy의 shape, size, dt

In [ ]:
#앞데이터 확인 = 기본 5
df.head()

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95
3  박민수   23   임베디드     80
4  성유고   25   인공지능    100

In [ ]:
# 기본5를 3으로 변경
df.head(3)

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   22   인공지능     95

In [30]:
#마지막데이터 확인
df.tail()

  name  age major  score
1  김철수   21   웹개발     90
2  이영희   22  인공지능     95
3  박민수   23  임베디드     80
4  성유고   25  인공지능    100
5  애슐리   26   웹개발     75

In [31]:
df.tail(2)

  name  age major  score
4  성유고   25  인공지능    100
5  애슐리   26   웹개발     75

In [32]:
# 형과 열의 개수
df.shape

(6, 4)

In [33]:
df.columns

Index(['name', 'age', 'major', 'score'], dtype='str')

In [34]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [35]:
# 컬럼별 타입과 결측값 확인
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   age     6 non-null      int64
 2   major   6 non-null      str
 3   score   6 non-null      int64
dtypes: int64(2), str(2)
memory usage: 324.0 bytes

#### 기본통계

In [37]:
df.describe()

             age       score
count   6.000000    6.000000
mean   22.833333   87.500000
std     2.316607    9.354143
min    20.000000   75.000000
25%    21.250000   81.250000
50%    22.500000   87.500000
75%    24.500000   93.750000
max    26.000000  100.000000

In [38]:
df.age.mean()

np.float64(22.833333333333332)

In [40]:
df['age'].mean()

np.float64(22.833333333333332)

In [41]:
df.age.median()

np.float64(22.5)

In [ ]:
# 25% 값/ 1분위수
df.age.quantile(0.25)

np.float64(21.25)

In [ ]:
# 2분위 수 = median()
df.age.quantile(0.5)

np.float64(22.5)